#!/bin/sh

# normdate - 日付指定の月のフィールドを大文字で始まる３文字のつきの名前に
# 変換する。あとのスクリプトNo.7の valid-date で使う。エラーがなければ
# 終了コード 0 で終了する

monthnoToName()
{
	# 変数 month に適切な値を設定する
	case $1 in
		1 ) month="Jan"		;;	2 ) month="Feb"		;;
		3 ) month="Mar"		;;	4 ) month="Apr"		;;
		5 ) month="May"		;;	6 ) month="Jun"		;;
		7 ) month="Jul"		;;	8 ) month="Aug"		;;
		9 )	month="Sep"		;; 	10)	month="Oct"		;;
		11)	month="Nov"		;;	12) month="Dec"		;;
		* )	echo "$0: Unknown numeric month value $1" >&2; exit 1
	esac
	return 0
}

# スクリプト本体の始まり

if [ $# -eq 1 ] ; then # /や-を使った日付の形式を扱えるようにする。
	set -- $(echo $1 | sed 's/[\/\-]/ /g')
fi

if [ $# -ne 3 ] ; then
	echo "Usage: $0 month day year " >&2
	echo "Typical Input formate are August 3 1962 and 8 3 2002" >&2
	exit 1
fi

if [ $3 -le 99 ] ; then
	echo "$0: expected four-digit year valuie." >&2; exit 1
fi

if [ -z $(echo $1|sed 's/[[:digit:]]//g') ] ; then
	monthnoToName $1
else
	# 3文字に統一する。先頭の文字は大文字に、残りは小文字にする。
	month="$(echo $1|cut -c1 | tr '[:lower:]' '[:upper:]')"
	month="$month$(echo $1|cut -c2-3 | tr	'[:upper:]' '[:lower:]')"
fi

echo $month $2 $3

exit 0
